config/routes.rb
Rails.application.routes.draw do
  scope module: :web do
    resources :articles do
      member do
        post :moderate
      end
      scope module: :articles do
        resources :comments do
          scope module: :comments do
            resources :likes, only: [:create]
          end
        end
      end
    end

    root 'welcome#index'
  end

  namespace :moderation do
    resources :articles, only: [:index, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, class_name: 'Article::Comment::Like'
  has_many :links, dependent: :destroy, inverse_of: :article

  belongs_to :category, required: false

  state_machine :state, initial: :draft do
    state :draft
    state :moderation
    state :published

    event :moderate do
      transition draft: :moderation
    end

    event :publish do
      transition moderation: :published
    end

    event :draft do
      transition moderation: :draft
    end
  end
end

app/models/article/category.rb
class Article::Category < ApplicationRecord
  has_many :articles
end

app/models/article/comment.rb
class Article::Comment < ApplicationRecord
  belongs_to :article
  has_many :likes, dependent: :delete_all

  def can_be_liked?
    likes_count_last_hour = likes.where('created_at >= ?', 1.hour.ago).count
    likes_count_last_hour < 5
  end
end

app/models/article/comment/like.rb
class Article::Comment::Like < ApplicationRecord
  belongs_to :comment, counter_cache: true
  belongs_to :article
end

app/models/article/link.rb
class Article::Link < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/moderation/application_controller.rb
module Moderation
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/moderation/articles_controller.rb
module Moderation
  class ArticlesController < ApplicationController
    def index
      default_ransack_params = { state_eq: 'moderation' }
      @q = Article.ransack(params[:q] || default_ransack_params)

      @articles = @q.result(distinct: true)
    end

    def edit
      @article = Moderation::ArticleType.find params[:id]
    end

    def update
      @article = Moderation::ArticleType.find params[:id]

      if @article.update(params.require(:article))
        redirect_to moderation_articles_path
      else
        render 'edit'
      end
    end
  end
end

app/controllers/web/application_controller.rb
module Web
  class ApplicationController < ::ApplicationController
    def self.authenticate!(options = {})
      settings = options.merge name: "viraj", password: "password"
      http_basic_authenticate_with settings
    end
  end
end

app/controllers/web/articles/application_controller.rb
module Web
  module Articles
    class ApplicationController < Web::ApplicationController
      def resource_article
        @resource_article ||= Article.find(params[:article_id] || params[:id])
      end
    end
  end
end

app/controllers/web/articles/comments/application_controller.rb
module Web
  module Articles
    module Comments
      class ApplicationController < Web::Articles::ApplicationController
        def resource_comment
          @resource_comment ||= resource_article.comments.find(params[:comment_id] || params[:id])
        end
      end
    end
  end
end

app/controllers/web/articles/comments/likes_controller.rb
module Web
  module Articles
    module Comments
      class LikesController < Web::Articles::Comments::ApplicationController
        def create
          Article::Comment::LikeMutator.create! resource_comment

          redirect_to article_path(resource_article)
        end
      end
    end
  end
end

app/controllers/web/articles/comments_controller.rb
module Web
  module Articles
    class CommentsController < Web::Articles::Comments::ApplicationController
      authenticate! only: :destroy

      def create
        @comment = resource_article.comments.create(comment_params)
        redirect_to article_path(resource_article)
      end

      def destroy
        resource_comment.destroy
        redirect_to article_path(resource_article)
      end

      private
      def comment_params
        params.require(:comment).permit(:commentor, :body)
      end
    end
  end
end

app/controllers/web/articles_controller.rb
module Web
  class ArticlesController < Articles::ApplicationController
    authenticate! except: [:index, :show]

    def index
      @articles = Article.all
      @article_likes_count = Article::Comment::Like.group(:article_id).count
    end

    def show
      @article = resource_article
    end

    def new
      @article = ArticleType.new
    end

    def create
      @article = ArticleType.new params.require(:article)

      if @article.save
        redirect_to @article
      else
        render 'new'
      end
    end

    def edit
      @article = ArticleType.find params[:id]
    end

    def update
      @article = ArticleType.find params[:id]

      if @article.update(params.require(:article))
        redirect_to @article
      else
        render 'edit'
      end
    end

    def moderate
      resource_article.moderate!
      redirect_to resource_article
    end

    def destroy
      resource_article.destroy
      redirect_to articles_path
    end
  end
end

app/controllers/web/welcome_controller.rb
module Web
  class WelcomeController < ApplicationController
    def index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commentor:</strong>
  <%= comment.commentor %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
<%= link_to 'Delete comment', [comment.article, comment],
method: :delete,
data: { confirm: 'Are you sure?' } %>
</p>
.........................................

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
      <%= link_to 'All articles', articles_path %>
      |
      <%= link_to 'Moderate articles', moderation_articles_path %>
    </p>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/moderation/articles/_form.html.slim
= simple_form_for @article, url: moderation_article_path(@article) do |f|
  = f.input :state_event, as: :state_event
  = f.association :category

  = f.button :submit

app/views/moderation/articles/edit.html.slim
h1 Moderate article

p
  strong Title:
  = @article.title

p
  strong Text:
  = @article.text

= render 'form'

p = link_to 'Back', moderation_articles_path

app/views/moderation/articles/index.html.slim
= search_form_for @q, url: moderation_articles_url do |f|
  = f.label :state_eq
  = f.select :state_eq, ['draft', 'moderation', 'published']

  = f.submit

h1 Articles:
table
  tr
    th Title
    th Text
    th = sort_link(@q, :created_at)

  - @articles.each do |article|
    tr
      td = article.title
      td = l article.created_at
      td = link_to 'Moderate', edit_moderation_article_path(article)

app/views/web/articles/_form.html.slim
= simple_form_for @article do |f|
  = f.input :title
  = f.input :text, as: :text

  h3 Links
  #links
    = f.simple_fields_for :links do |link|
      = render 'web/articles/links/link_fields', f: link
    .links
      = link_to_add_association 'add link',
                                f,
                                :links,
                                force_non_association_create: true,
                                partial: 'web/articles/links/link_fields'

  = f.button :submit

app/views/web/articles/comments/_comment.html.slim
p
  strong Commentor:
  = comment.commentor

p
  strong Comment:
  = comment.body
  br
  = link_to "Like (#{comment.likes_count})", article_comment_likes_path(comment.article, comment), method: :post

p
  = link_to 'Delete comment', article_comment_path(comment.article, comment), method: :delete, data: { confirm: 'Are you sure?' }

| .........................................

app/views/web/articles/comments/_form.html.slim
= form_with(model: @article.comments.build, url: article_comments_path(@article), scope: :comment) do |form|
  p
    = form.label :commentor
    br
    = form.text_field :commentor, id: :comment_commentor
  p
    = form.label :body
    br
    = form.text_area :body, id: :comment_body
  p
    = form.submit

app/views/web/articles/edit.html.slim
h1 Edit article

= render 'form'

p = link_to 'Back', articles_path

app/views/web/articles/index.html.slim
h1 Articles:

p
  = link_to 'New article', new_article_path

table
  tr
    th Title
    th Text
    th Likes
  - @articles.each do |article|
    tr
      td = article.title
      td = article.text
      td = @article_likes_count[article.id]
      td = link_to 'Show', article_path(article)
      td = link_to 'Edit', edit_article_path(article)
      td = link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }

app/views/web/articles/links/_link_fields.html.slim
.nested-fields
  = f.input :url, as: :string
  = link_to_remove_association "remove link", f

app/views/web/articles/new.html.slim
h1 New article

= render 'form'

p = link_to 'Back', articles_path

app/views/web/articles/show.html.slim
p
  strong Title:
  = @article.title

p
  strong Text:
  = @article.text

h2 Links
ul
  - @article.links.each do |link|
    li = link_to link.url

h2 Comments
= render partial: 'web/articles/comments/comment',
         collection: @article.comments

h2 Add a comment:
= render 'web/articles/comments/form'

p
  => link_to 'Edit', edit_article_path(@article)
  ' |
  => link_to 'Back', articles_path
  ' |
  = link_to 'Moderate', moderate_article_path(@article), method: :post

app/views/web/welcome/index.html.slim
h1 Blog
= link_to 'My Blog', controller: 'articles'